# ===== Frontend (Next.js + TypeScript) =====
FROM node:20-alpine AS builder

WORKDIR /app
COPY ../frontend/package*.json ./
RUN npm install

COPY ../frontend .

ENV NEXT_PUBLIC_API_URL=http://backend:3001/api
RUN npm run build

# ===== Runner =====
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=http://backend:3001/api

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]
